services:
  - type: web
    name: barcode-api
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --timeout 0 --preload"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
